### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open

### ISSUE THREAD

**Issue by lastkoh** [Marsan-Ma/tf_chatbot_seq2seq_antilm#32]
I bump into the issue while trying to train based on the data from [twitter_en-big](https://github.com/Marsan-Ma/chat_corpus#5-twitter_en-big)

`python main.py --mode train --model_name twitter_en_big`

My working environment is:
Windows 10 64 bit
Python 3.5
tensorflow-gpu v1.0.0

One more thing that I need to confirm is my file naming correct for the train and test data?

D:\Dev-Projects\tf_chatbot_seq2seq_antilm\works\twitter_en_big\data\train\chat.test.gz
D:\Dev-Projects\tf_chatbot_seq2seq_antilm\works\twitter_en_big\data\test\chat_test.txt

```
Created model with fresh parameters.
Reading development and training data (limit: 0).
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    tf.app.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 18, in main
    train(args)
  File "D:\Dev-Projects\tf_chatbot_seq2seq_antilm\lib\train.py", line 48, in train
    dev_set = data_utils.read_data(dev_data, args.buckets, reversed=args.rev_model)
  File "D:\Dev-Projects\tf_chatbot_seq2seq_antilm\lib\data_utils.py", line 399, in read_data
    source, target = fh.readline(), fh.readline()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 123, in readline
    self._preread_check()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 73, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: works/twitter_en_big/data\chat_test.ids100000.in : The system cannot find the file specified.

```

**Comment by ssapra1** [comment]
you need to create chat_test.ids100000.in and chat.ids100000.in file , this will resolve the issue but after that what needs to be put in that file . Can someone explain this? After this i am getting

Traceback (most recent call last):
  File "main.py", line 28, in <module>
    tf.app.run()
  File "C:\Users\Dell\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 18, in main
    train(args)
  File "C:\Users\Dell\Downloads\tf_chatbot_seq2seq_antilm-master\lib\train.py", line 57, in train
    for i in xrange(len(train_bucket_sizes))]
  File "C:\Users\Dell\Downloads\tf_chatbot_seq2seq_antilm-master\lib\train.py", line 57, in <listcomp>
    for i in xrange(len(train_bucket_sizes))]
ZeroDivisionError: float division by zero

**Comment by ssapra1** [comment]
Change in the train.py , as given below as 

 if not os.path.exists("%s/chat.in" % data_dir):
    n = 0
    f_zip   = gzip.open("%s/train/chat.txt.gz" % data_dir,'rb')
    f_train = open("%s/chat.in" % data_dir, 'wb')
    f_dev   = open("%s/chat_test.in" % data_dir, 'wb')


rb == Read bytes 
wb==write bytes
