### ISSUE TITLE
Unexpected keyword argument 'training'

### ISSUE THREAD

**Issue by Sashweed** [Marsan-Ma/tf_chatbot_seq2seq_antilm#8]
Afternoon Marsan,

I have spent the last few weeks trying to get your code setup and running. Unfortunately in this time they have released TF v1.0 and seq2seq has been deprecated. I have spent the last few days fixing all the changes to make it 1.0 compatable (I have a fork of this and will push when I have finished testing) but there is 1 error I can't fix

```
jxx@Eve:~/sashweed/tf_chatbot_seq2seq_antilm$ python3 main.py --mode train --model_name opensubs
[args]:  Namespace(antilm=0, batch_size=128, beam_size=10, buckets=[(5, 10), (10, 15), (20, 25), (40, 50)], data_dir='works/opensubs/data', en_tfboard=0, gpu_usage=1, learning_rate=0.5, learning_rate_decay_factor=0.99, max_gradient_norm=5.0, max_train_data_size=0, mert_dataset_path='works/opensubs/data/test/mert_set.txt', mode='train', model_dir='works/opensubs/nn_models', model_name='opensubs', n_bonus=0, num_layers=4, reinforce_learn=0, results_dir='works/opensubs/results', rev_model=0, scope_name='opensubs', size=128, steps_per_checkpoint=1000, test_dataset_path='works/opensubs/data/test/test_set.txt', tf_board_dir='works/opensubs/tf_board', vocab_size=100000, work_root='works', workspace='works/opensubs')
[opensubs] Preparing dialog data in works/opensubs/data
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Creating 4 layers of 128 units.
Created model with fresh parameters.
Reading development and training data (limit: 0).
  reading data line 100000
  reading data line 200000
  reading data line 300000
  reading data line 400000
  reading data line 500000
  reading data line 600000
  reading data line 700000
  reading data line 800000
  reading data line 900000
  reading data line 1000000
  reading data line 1100000
  reading data line 1200000
  reading data line 1300000
  reading data line 1400000
  reading data line 1500000
  reading data line 1600000
  reading data line 1700000
  reading data line 1800000
  reading data line 1900000
  reading data line 2000000
  reading data line 2100000
  reading data line 2200000
  reading data line 2300000
  reading data line 2400000
  reading data line 2500000
  reading data line 2600000
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 18, in main
    train(args)
  File "/home/jxx/sashweed/tf_chatbot_seq2seq_antilm/lib/train.py", line 86, in train
    target_weights, bucket_id, training=True, force_dec_input=True)
TypeError: step() got an unexpected keyword argument 'training'
jxx@Eve:~/sashweed/tf_chatbot_seq2seq_antilm$
```
do you have any idea why this might be erroring.

I have tried removing the 2 arguments and that resulted in a different error complaining there weren't enough arguments.

Thanks in advance for your assistance.

J

**Comment by Marsan-Ma** [comment]
Forget about the old version, I've updated the code to support tensorflow v1.0.0, yay!

**Comment by Sashweed** [comment]
Amazing thank you so much. 

I'll test as soon as I get back to work in April. 

Thanks again for your skills.
